name: slide_puzzle_shared
description: Shared logic used on both client and server for the slide puzzle.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  bloc: ^8.0.1
  equatable: ^2.0.3


dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec